export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";

export const AUTH_SIGNUP = "AUTH_SIGNUP";
export const AUTH_SIGNUP_SUCCESS = "AUTH_SIGNUP_SUCCESS";
export const AUTH_SIGNUP_FAILURE = "AUTH_SIGNUP_FAILURE";

export const AUTH_FETCH_USER = "AUTH_FETCH_USER";
export const AUTH_FETCH_USER_SUCCESS = "AUTH_FETCH_USER_SUCCESS";
export const AUTH_FETCH_USER_FAILURE = "AUTH_FETCH_USER_FAILURE";

export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const OPEN_DIALOG = "[DIALOG] OPEN";
export const CLOSE_DIALOG = "[DIALOG] CLOSE";

export const HIDE_MESSAGE = "[MESSAGE] CLOSE";
export const SHOW_MESSAGE = "[MESSAGE] SHOW";

export const OPEN_FOLDED_NAVBAR = "[NAVBAR] OPEN FOLDED";
export const CLOSE_FOLDED_NAVBAR = "[NAVBAR] CLOSE FOLDED";
export const TOGGLE_FOLDED_NAVBAR = "[NAVBAR] TOGGLE FOLDED";
export const TOGGLE_MOBILE_NAVBAR = "[NAVBAR] TOGGLE MOBILE";
export const OPEN_MOBILE_NAVBAR = "[NAVBAR] OPEN MOBILE";
export const CLOSE_MOBILE_NAVBAR = "[NAVBAR] CLOSE MOBILE";

export const GET_NAVIGATION = "[NAVIGATION] GET NAVIGATION";
export const SET_NAVIGATION = "[NAVIGATION] SET NAVIGATION";
export const RESET_NAVIGATION = "[NAVIGATION] RESET NAVIGATION";

export const SET_SETTINGS = "[SETTINGS] SET SETTINGS";
export const SET_DEFAULT_SETTINGS = "[SETTINGS] SET DEFAULT SETTINGS";
export const SET_INITIAL_SETTINGS = "[SETTINGS] SET INITIAL SETTINGS";
export const RESET_DEFAULT_SETTINGS = "[SETTINGS] RESET DEFAULT SETTINGS";

export const NOTIFICATIONS_ENQUEUE_SNACKBAR = "NOTIFICATIONS_ENQUEUE_SNACKBAR";
export const NOTIFICATIONS_CLOSE_SNACKBAR = "NOTIFICATIONS_CLOSE_SNACKBAR";
export const NOTIFICATIONS_REMOVE_SNACKBAR = "NOTIFICATIONS_REMOVE_SNACKBAR";

export const EVENTS_FETCH_ALL_EVENTS = "EVENTS_FETCH_ALL_EVENTS";
export const EVENTS_FETCH_ALL_EVENTS_SUCCESS = "EVENTS_FETCH_ALL_EVENTS_SUCCESS";
export const EVENTS_FETCH_ALL_EVENTS_FAILURE = "EVENTS_FETCH_ALL_EVENTS_FAILURE";

export const EVENTS_ADD_EVENTS = "EVENTS_ADD_EVENTS";
export const EVENTS_ADD_EVENTS_SUCCESS = "EVENTS_ADD_EVENTS_SUCCESS";
export const EVENTS_ADD_EVENTS_FAILURE = "EVENTS_ADD_EVENTS_FAILURE";

export const EVENTS_EDIT_EVENTS = "EVENTS_EDIT_EVENTS";
export const EVENTS_EDIT_EVENTS_SUCCESS = "EVENTS_EDIT_EVENTS_SUCCESS";
export const EVENTS_EDIT_EVENTS_FAILURE = "EVENTS_EDIT_EVENTS_FAILURE";

export const EVENTS_DELETE_EVENTS = "EVENTS_DELETE_EVENTS";
export const EVENTS_DELETE_EVENTS_SUCCESS = "EVENTS_DELETE_EVENTS_SUCCESS";
export const EVENTS_DELETE_EVENTS_FAILURE = "EVENTS_DELETE_EVENTS_FAILURE";

export const COMMON_UPLOAD_IMAGE = "COMMON_UPLOAD_IMAGE";
export const COMMON_UPLOAD_IMAGE_SUCCESS = "COMMON_UPLOAD_IMAGE_SUCCESS";
export const COMMON_UPLOAD_IMAGE_FAILURE = "COMMON_UPLOAD_IMAGE_FAILURE";

export const COMMON_UPLOAD_IMAGE_URL_HANDLING = "COMMON_UPLOAD_IMAGE_URL_HANDLING";

